version: "3" # composeファイルのバージョン
services: 
    app: # サービス名
        build: 
            context: . # ビルドに使うDockerfileの場所
            dockerfile: Dockerfile
        tty: true # コンテナの永続化
        ports: # ホストOSのポートとコンテナのポートをつなげる
            - "3000:3000"
        working_dir: /home/lottery-react
        volumes:
            - ./:/home/lottery-react # マウントディレクトリ